
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles Table
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  name text,
  email text,
  role text default 'user',
  plan text default 'Free',
  bio text,
  profession text,
  interests text,
  goals text,
  onboarding_completed boolean default false,
  team_members text[],
  trial_start_date timestamp with time zone
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );


-- 2. Conversations Table
-- We handle potential existing camelCase columns by renaming them to snake_case to match the new code.
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text,
  source_lang text,
  target_lang text,
  tone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- MIGRATION: Rename columns if they exist in camelCase (fix for PGRST204)
DO $$
BEGIN
    -- Rename sourceLang -> source_lang
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'conversations' AND column_name = 'sourceLang') THEN
        ALTER TABLE public.conversations RENAME COLUMN "sourceLang" TO source_lang;
    ELSIF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'conversations' AND column_name = 'sourcelang') THEN
        ALTER TABLE public.conversations RENAME COLUMN sourcelang TO source_lang;
    END IF;

    -- Rename targetLang -> target_lang
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'conversations' AND column_name = 'targetLang') THEN
        ALTER TABLE public.conversations RENAME COLUMN "targetLang" TO target_lang;
    ELSIF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'conversations' AND column_name = 'targetlang') THEN
        ALTER TABLE public.conversations RENAME COLUMN targetlang TO target_lang;
    END IF;
    
    -- Ensure columns exist if table was created empty
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'conversations' AND column_name = 'source_lang') THEN
        ALTER TABLE public.conversations ADD COLUMN source_lang text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'conversations' AND column_name = 'target_lang') THEN
        ALTER TABLE public.conversations ADD COLUMN target_lang text;
    END IF;
END $$;

alter table public.conversations enable row level security;

create policy "Users can view their own conversations" on public.conversations for select using ( auth.uid() = user_id );
create policy "Users can insert their own conversations" on public.conversations for insert with check ( auth.uid() = user_id );
create policy "Users can update their own conversations" on public.conversations for update using ( auth.uid() = user_id );
create policy "Users can delete their own conversations" on public.conversations for delete using ( auth.uid() = user_id );


-- 3. Chat Messages Table
-- Note: We use quoted identifiers ("originalText") here because the frontend code explicitly 
-- sends them as camelCase strings in the INSERT statements.
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations on delete cascade not null,
  role text not null,
  "originalText" text, 
  translation jsonb,
  rating text,
  attachments jsonb,
  "groundingSources" jsonb,
  "imageURL" text,
  "originalAudioFileName" text,
  "isOfflineTranslation" boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.chat_messages enable row level security;

create policy "Users can view messages from their conversations" on public.chat_messages for select using ( 
  exists ( select 1 from public.conversations where id = chat_messages.conversation_id and user_id = auth.uid() ) 
);
create policy "Users can insert messages into their conversations" on public.chat_messages for insert with check ( 
  exists ( select 1 from public.conversations where id = conversation_id and user_id = auth.uid() ) 
);


-- 4. Library Items Table
create table if not exists public.library_items (
  id bigint generated by default as identity primary key,
  type text not null,
  text text not null,
  source text not null,
  target text not null,
  tone text,
  meaning text not null,
  "audioUrl" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.library_items enable row level security;

create policy "Library items are viewable by everyone" on public.library_items for select using ( true );
create policy "Admins can insert library items" on public.library_items for insert with check ( 
  exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' )
);
create policy "Admins can update library items" on public.library_items for update using ( 
  exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' )
);
create policy "Admins can delete library items" on public.library_items for delete using ( 
  exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' )
);


-- 5. Scheduled Meetings Table
create table if not exists public.scheduled_meetings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  meeting_link text,
  scheduled_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.scheduled_meetings enable row level security;

create policy "Users can view their own scheduled meetings" on public.scheduled_meetings for select using ( auth.uid() = user_id );
create policy "Users can insert their own scheduled meetings" on public.scheduled_meetings for insert with check ( auth.uid() = user_id );
create policy "Users can delete their own scheduled meetings" on public.scheduled_meetings for delete using ( auth.uid() = user_id );


-- 6. Meeting Summaries Table
create table if not exists public.meeting_summaries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  meeting_link text,
  file_name text,
  transcript text,
  summary text,
  language text,
  mode text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.meeting_summaries enable row level security;

create policy "Users can view their own meeting summaries" on public.meeting_summaries for select using ( auth.uid() = user_id );
create policy "Users can insert their own meeting summaries" on public.meeting_summaries for insert with check ( auth.uid() = user_id );

-- Meeting Insights tables added 2026-04-02

create table if not exists public.meeting_insight_jobs (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references profiles(id) on delete cascade,
  source_type text not null check (source_type in ('meeting_link', 'recording_upload')),
  source_url text,
  recording_bucket text,
  recording_path text,
  output_language_code text not null,
  transcription_style text not null check (transcription_style in ('verbatim', 'clean_read', 'executive_summary')),
  localization_mode text not null check (localization_mode in ('direct_translation', 'deep_localized')),
  status text not null default 'queued' check (status in ('queued','uploading','transcribing','localizing','extracting_insights','exporting','succeeded','failed')),
  stage text,
  progress integer default 0,
  result_json jsonb,
  executive_summary text,
  language_note text,
  retry_count integer default 0,
  error_code text,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.meeting_insight_segments (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references meeting_insight_jobs(id) on delete cascade,
  segment_index integer not null,
  start_ms integer,
  end_ms integer,
  speaker_label text,
  language_code text,
  original_text text,
  localized_text text,
  is_inaudible boolean default false,
  confidence numeric,
  unique(job_id, segment_index)
);

create table if not exists public.meeting_insight_exports (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references meeting_insight_jobs(id) on delete cascade,
  format text not null check (format in ('txt','srt','pdf','docx')),
  bucket text,
  path text,
  file_name text,
  mime_type text,
  size_bytes integer,
  created_at timestamptz default now(),
  unique(job_id, format)
);

create index if not exists idx_meeting_insight_jobs_user_id_created_at_desc on public.meeting_insight_jobs (user_id, created_at desc);
create index if not exists idx_meeting_insight_jobs_status on public.meeting_insight_jobs (status);
create index if not exists idx_meeting_insight_segments_job_id on public.meeting_insight_segments (job_id);
create index if not exists idx_meeting_insight_exports_job_id on public.meeting_insight_exports (job_id);
