
/* 
  ------------------------------------------------------------------
  AfriTranslate AI - History Tab Setup
  Run this in the Supabase SQL Editor to enable the History feature.
  ------------------------------------------------------------------
*/

-- 1. Create Conversations Table
-- Stores the metadata for each chat session shown in the sidebar.
CREATE TABLE IF NOT EXISTS public.conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT,
  source_lang TEXT,
  target_lang TEXT,
  tone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Chat Messages Table
-- Stores the individual messages. 
-- Note: We use quoted identifiers (e.g., "originalText") to match the camelCase fields used in the React App.
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
  role TEXT NOT NULL, -- 'user' or 'ai'
  "originalText" TEXT, 
  translation JSONB, -- Stores the JSON object with culturallyAwareTranslation, explanation, etc.
  rating TEXT, -- 'good' or 'bad'
  attachments JSONB, -- Array of file metadata
  "groundingSources" JSONB, -- Array of source links
  "imageURL" TEXT,
  "originalAudioFileName" TEXT,
  "isOfflineTranslation" BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable Row Level Security (RLS)
-- This ensures that users cannot access data belonging to others.
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- 4. Define Policies for Conversations
-- Allow users to fully manage their own conversation threads.

CREATE POLICY "Users can view own conversations" 
ON public.conversations FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own conversations" 
ON public.conversations FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own conversations" 
ON public.conversations FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own conversations" 
ON public.conversations FOR DELETE 
USING (auth.uid() = user_id);

-- 5. Define Policies for Chat Messages
-- Allow users to manage messages only if they own the parent conversation.

CREATE POLICY "Users can view messages of own conversations" 
ON public.chat_messages FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.conversations 
    WHERE id = chat_messages.conversation_id 
    AND user_id = auth.uid()
  )
);

CREATE POLICY "Users can insert messages to own conversations" 
ON public.chat_messages FOR INSERT 
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.conversations 
    WHERE id = conversation_id 
    AND user_id = auth.uid()
  )
);

-- 6. Create Indexes for Performance
-- Optimize the sidebar loading and message history sorting.

CREATE INDEX IF NOT EXISTS idx_conversations_user_created 
ON public.conversations(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_created 
ON public.chat_messages(conversation_id, created_at ASC);
