
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Scheduled Meetings Table
create table if not exists public.scheduled_meetings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  meeting_link text,
  scheduled_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.scheduled_meetings enable row level security;

-- Policies
create policy "Users can view their own scheduled meetings"
on public.scheduled_meetings for select
using ( auth.uid() = user_id );

create policy "Users can insert their own scheduled meetings"
on public.scheduled_meetings for insert
with check ( auth.uid() = user_id );

create policy "Users can delete their own scheduled meetings"
on public.scheduled_meetings for delete
using ( auth.uid() = user_id );


-- 2. Meeting Summaries Table (Required for storing results)
create table if not exists public.meeting_summaries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  meeting_link text,
  file_name text,
  transcript text,
  summary text,
  language text,
  mode text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.meeting_summaries enable row level security;

create policy "Users can view their own meeting summaries"
on public.meeting_summaries for select
using ( auth.uid() = user_id );

create policy "Users can insert their own meeting summaries"
on public.meeting_summaries for insert
with check ( auth.uid() = user_id );


-- 3. Conversations Table (Chat history)
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text,
  "sourceLang" text,
  "targetLang" text,
  tone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.conversations enable row level security;

create policy "Users can view their own conversations"
on public.conversations for select
using ( auth.uid() = user_id );

create policy "Users can insert their own conversations"
on public.conversations for insert
with check ( auth.uid() = user_id );

create policy "Users can update their own conversations"
on public.conversations for update
using ( auth.uid() = user_id );


-- 4. Chat Messages Table
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations on delete cascade not null,
  role text not null,
  "originalText" text,
  translation jsonb,
  rating text,
  attachments jsonb,
  "groundingSources" jsonb,
  "imageURL" text,
  "originalAudioFileName" text,
  "isOfflineTranslation" boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.chat_messages enable row level security;

create policy "Users can view messages from their conversations"
on public.chat_messages for select
using ( 
  exists (
    select 1 from public.conversations 
    where id = chat_messages.conversation_id 
    and user_id = auth.uid()
  ) 
);

create policy "Users can insert messages into their conversations"
on public.chat_messages for insert
with check ( 
  exists (
    select 1 from public.conversations 
    where id = conversation_id 
    and user_id = auth.uid()
  ) 
);


-- 5. Profiles Table
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  name text,
  email text,
  role text default 'user',
  plan text default 'Free',
  bio text,
  profession text,
  interests text,
  goals text,
  onboarding_completed boolean default false,
  team_members text[],
  trial_start_date timestamp with time zone
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );


-- 6. Library Items Table
create table if not exists public.library_items (
  id bigint generated by default as identity primary key,
  type text not null,
  text text not null,
  source text not null,
  target text not null,
  tone text,
  meaning text not null,
  "audioUrl" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.library_items enable row level security;

create policy "Library items are viewable by everyone"
on public.library_items for select
using ( true );

create policy "Admins can insert library items"
on public.library_items for insert
with check ( 
  exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
);

create policy "Admins can update library items"
on public.library_items for update
using ( 
  exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
);

create policy "Admins can delete library items"
on public.library_items for delete
using ( 
  exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
);
