-- ============================================================================
-- Migration Version: v1.0.0-studio-features
-- Created: 2026-02-16
-- Description: Adds Studio feature tables (cultural_insights, brand_glossaries)
--              with proper foreign keys and RLS policies
-- Safety: Uses CREATE TABLE IF NOT EXISTS - safe for production
-- ============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- TABLE: cultural_insights
-- Purpose: Store cultural context and insights for translations
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.cultural_insights (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  language text NOT NULL,
  category text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  examples jsonb DEFAULT '[]'::jsonb,
  tags text[] DEFAULT '{}'::text[],
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_cultural_insights_user_id ON public.cultural_insights(user_id);
CREATE INDEX IF NOT EXISTS idx_cultural_insights_language ON public.cultural_insights(language);
CREATE INDEX IF NOT EXISTS idx_cultural_insights_category ON public.cultural_insights(category);
CREATE INDEX IF NOT EXISTS idx_cultural_insights_is_public ON public.cultural_insights(is_public);

-- Enable RLS
ALTER TABLE public.cultural_insights ENABLE ROW LEVEL SECURITY;

-- RLS Policies for cultural_insights
DO $$ 
BEGIN
  -- Drop existing policies if they exist (idempotent)
  DROP POLICY IF EXISTS "Users can view their own cultural insights" ON public.cultural_insights;
  DROP POLICY IF EXISTS "Users can view public cultural insights" ON public.cultural_insights;
  DROP POLICY IF EXISTS "Users can insert their own cultural insights" ON public.cultural_insights;
  DROP POLICY IF EXISTS "Users can update their own cultural insights" ON public.cultural_insights;
  DROP POLICY IF EXISTS "Users can delete their own cultural insights" ON public.cultural_insights;
  
  -- Create policies
  CREATE POLICY "Users can view their own cultural insights" 
    ON public.cultural_insights FOR SELECT 
    USING (auth.uid() = user_id);
  
  CREATE POLICY "Users can view public cultural insights" 
    ON public.cultural_insights FOR SELECT 
    USING (is_public = true);
  
  CREATE POLICY "Users can insert their own cultural insights" 
    ON public.cultural_insights FOR INSERT 
    WITH CHECK (auth.uid() = user_id);
  
  CREATE POLICY "Users can update their own cultural insights" 
    ON public.cultural_insights FOR UPDATE 
    USING (auth.uid() = user_id);
  
  CREATE POLICY "Users can delete their own cultural insights" 
    ON public.cultural_insights FOR DELETE 
    USING (auth.uid() = user_id);
END $$;


-- ============================================================================
-- TABLE: brand_glossaries
-- Purpose: Store brand-specific terminology and translation preferences
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.brand_glossaries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  brand_name text NOT NULL,
  source_language text NOT NULL,
  target_language text NOT NULL,
  term text NOT NULL,
  translation text NOT NULL,
  context text,
  notes text,
  category text,
  is_approved boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT unique_brand_term_languages UNIQUE (user_id, brand_name, source_language, target_language, term)
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_brand_glossaries_user_id ON public.brand_glossaries(user_id);
CREATE INDEX IF NOT EXISTS idx_brand_glossaries_brand_name ON public.brand_glossaries(brand_name);
CREATE INDEX IF NOT EXISTS idx_brand_glossaries_languages ON public.brand_glossaries(source_language, target_language);
CREATE INDEX IF NOT EXISTS idx_brand_glossaries_term ON public.brand_glossaries(term);

-- Enable RLS
ALTER TABLE public.brand_glossaries ENABLE ROW LEVEL SECURITY;

-- RLS Policies for brand_glossaries
DO $$ 
BEGIN
  -- Drop existing policies if they exist (idempotent)
  DROP POLICY IF EXISTS "Users can view their own brand glossaries" ON public.brand_glossaries;
  DROP POLICY IF EXISTS "Users can insert their own brand glossaries" ON public.brand_glossaries;
  DROP POLICY IF EXISTS "Users can update their own brand glossaries" ON public.brand_glossaries;
  DROP POLICY IF EXISTS "Users can delete their own brand glossaries" ON public.brand_glossaries;
  
  -- Create policies
  CREATE POLICY "Users can view their own brand glossaries" 
    ON public.brand_glossaries FOR SELECT 
    USING (auth.uid() = user_id);
  
  CREATE POLICY "Users can insert their own brand glossaries" 
    ON public.brand_glossaries FOR INSERT 
    WITH CHECK (auth.uid() = user_id);
  
  CREATE POLICY "Users can update their own brand glossaries" 
    ON public.brand_glossaries FOR UPDATE 
    USING (auth.uid() = user_id);
  
  CREATE POLICY "Users can delete their own brand glossaries" 
    ON public.brand_glossaries FOR DELETE 
    USING (auth.uid() = user_id);
END $$;


-- ============================================================================
-- TRIGGER: Update updated_at timestamp automatically
-- ============================================================================

-- Create or replace the update timestamp function
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach triggers to tables
DROP TRIGGER IF EXISTS update_cultural_insights_updated_at ON public.cultural_insights;
CREATE TRIGGER update_cultural_insights_updated_at
  BEFORE UPDATE ON public.cultural_insights
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_brand_glossaries_updated_at ON public.brand_glossaries;
CREATE TRIGGER update_brand_glossaries_updated_at
  BEFORE UPDATE ON public.brand_glossaries
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();


-- ============================================================================
-- VERIFICATION QUERIES (Optional - comment out in production)
-- ============================================================================

-- Uncomment these to verify the migration after running:
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name IN ('cultural_insights', 'brand_glossaries');
-- SELECT * FROM information_schema.table_constraints WHERE table_name IN ('cultural_insights', 'brand_glossaries');
-- SELECT schemaname, tablename, policyname FROM pg_policies WHERE tablename IN ('cultural_insights', 'brand_glossaries');


-- ============================================================================
-- Migration Complete
-- ============================================================================
