import { supabaseAdmin } from './_supabase';
import type { TranscriptSegment, MeetingInsightsResult } from '../../src/types';

// ── Timestamp formatter ────────────────────────────────────────────────────────

function msToTimestamp(ms: number): string {
  const totalSeconds = Math.floor(ms / 1000);
  const h = Math.floor(totalSeconds / 3600);
  const m = Math.floor((totalSeconds % 3600) / 60);
  const s = totalSeconds % 60;
  const ms3 = Math.floor(ms % 1000);
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')},${String(ms3).padStart(3, '0')}`;
}

function msToReadable(ms: number | null): string {
  if (ms == null) return '';
  const m = Math.floor(ms / 60000);
  const s = Math.floor((ms % 60000) / 1000);
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

// ── TXT Builder ────────────────────────────────────────────────────────────────

export function buildTXT(
  segments: TranscriptSegment[],
  insights: MeetingInsightsResult,
  jobId: string
): string {
  const lines: string[] = [];

  lines.push('═══════════════════════════════════════════════════════');
  lines.push('  AFRITRANSLATE AI — MEETING INSIGHTS REPORT');
  lines.push(`  Job ID: ${jobId}`);
  lines.push(`  Generated: ${new Date().toUTCString()}`);
  lines.push('═══════════════════════════════════════════════════════');
  lines.push('');

  lines.push('── EXECUTIVE SUMMARY ──────────────────────────────────');
  lines.push(insights.executiveSummary);
  lines.push('');

  lines.push('── KEY DISCUSSION POINTS ──────────────────────────────');
  insights.keyPoints.forEach((p, i) => lines.push(`  ${i + 1}. ${p}`));
  lines.push('');

  lines.push('── DECISIONS MADE ─────────────────────────────────────');
  if (insights.decisions.length > 0) {
    insights.decisions.forEach((d, i) => lines.push(`  ${i + 1}. ${d}`));
  } else {
    lines.push('  No explicit decisions recorded.');
  }
  lines.push('');

  lines.push('── ACTION ITEMS ───────────────────────────────────────');
  if (insights.actionItems.length > 0) {
    insights.actionItems.forEach((a, i) => {
      const owner = a.assignedSpeaker ? ` [${a.assignedSpeaker}]` : '';
      lines.push(`  ${i + 1}.${owner} ${a.description}`);
    });
  } else {
    lines.push('  No action items recorded.');
  }
  lines.push('');

  lines.push('── HIGHLIGHTS ─────────────────────────────────────────');
  insights.highlights.forEach((h, i) => lines.push(`  ${i + 1}. ${h}`));
  lines.push('');

  lines.push('── LANGUAGE NOTE ──────────────────────────────────────');
  lines.push(`  Original language(s): ${insights.languageNote.originalLanguages.join(', ')}`);
  lines.push(`  Output language: ${insights.languageNote.outputLanguage}`);
  lines.push(`  Localization level: ${insights.languageNote.localizationLevel}`);
  lines.push('');

  lines.push('── FULL TRANSCRIPT ────────────────────────────────────');
  segments.forEach((s) => {
    const time = s.startMs != null ? `[${msToReadable(s.startMs)}] ` : '';
    const speaker = s.speakerLabel ?? 'Speaker';
    const text = s.localizedText ?? s.originalText;
    lines.push(`${time}${speaker}: ${text}`);
  });
  lines.push('');
  lines.push('═══════════════════════════════════════════════════════');
  lines.push('  Generated by AfriTranslate AI — afritranslate.co.za');
  lines.push('═══════════════════════════════════════════════════════');

  return lines.join('\n');
}

// ── SRT Builder ────────────────────────────────────────────────────────────────

export function buildSRT(segments: TranscriptSegment[]): string {
  const blocks: string[] = [];
  let counter = 1;

  for (const s of segments) {
    if (s.isInaudible) continue;
    const start = s.startMs != null ? msToTimestamp(s.startMs) : '00:00:00,000';
    const end = s.endMs != null ? msToTimestamp(s.endMs) : msToTimestamp((s.startMs ?? 0) + 3000);
    const text = s.localizedText ?? s.originalText;
    const speaker = s.speakerLabel ? `${s.speakerLabel}: ` : '';

    blocks.push(`${counter}`);
    blocks.push(`${start} --> ${end}`);
    blocks.push(`${speaker}${text}`);
    blocks.push('');
    counter++;
  }

  return blocks.join('\n');
}

// ── PDF Builder ────────────────────────────────────────────────────────────────

export async function buildPDF(
  segments: TranscriptSegment[],
  insights: MeetingInsightsResult,
  jobId: string
): Promise<Buffer> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const addText = (text: string, size = 10, bold = false) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, maxWidth);
    if (y + lines.length * (size * 0.4) > 280) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, margin, y);
    y += lines.length * (size * 0.45) + 2;
  };

  const addSection = (title: string) => {
    y += 4;
    addText(title, 11, true);
    y += 1;
  };

  addText('AfriTranslate AI — Meeting Insights Report', 16, true);
  addText(`Job ID: ${jobId}  |  Generated: ${new Date().toLocaleDateString()}`, 8);
  y += 6;

  addSection('Executive Summary');
  addText(insights.executiveSummary);

  addSection('Key Discussion Points');
  insights.keyPoints.forEach((p, i) => addText(`${i + 1}. ${p}`));

  addSection('Decisions Made');
  if (insights.decisions.length > 0) {
    insights.decisions.forEach((d, i) => addText(`${i + 1}. ${d}`));
  } else {
    addText('No explicit decisions recorded.');
  }

  addSection('Action Items');
  if (insights.actionItems.length > 0) {
    insights.actionItems.forEach((a, i) => {
      const owner = a.assignedSpeaker ? ` [${a.assignedSpeaker}]` : '';
      addText(`${i + 1}.${owner} ${a.description}`);
    });
  } else {
    addText('No action items recorded.');
  }

  addSection('Highlights');
  insights.highlights.forEach((h, i) => addText(`${i + 1}. ${h}`));

  addSection('Language Note');
  addText(`Original: ${insights.languageNote.originalLanguages.join(', ')} → Output: ${insights.languageNote.outputLanguage} (${insights.languageNote.localizationLevel})`);

  doc.addPage();
  y = 20;
  addText('Full Transcript', 13, true);
  y += 4;
  segments.forEach((s) => {
    const time = s.startMs != null ? `[${msToReadable(s.startMs)}] ` : '';
    const speaker = s.speakerLabel ?? 'Speaker';
    const text = s.localizedText ?? s.originalText;
    addText(`${time}${speaker}: ${text}`, 9);
  });

  return Buffer.from(doc.output('arraybuffer'));
}

// ── DOCX Builder ───────────────────────────────────────────────────────────────

export async function buildDOCX(
  segments: TranscriptSegment[],
  insights: MeetingInsightsResult,
  jobId: string
): Promise<Buffer> {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel } = await import('docx');

  const heading = (text: string) =>
    new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 100 } });

  const body = (text: string) =>
    new Paragraph({ children: [new TextRun({ text, size: 20 })], spacing: { after: 80 } });

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({
          text: 'AfriTranslate AI — Meeting Insights Report',
          heading: HeadingLevel.HEADING_1,
        }),
        body(`Job ID: ${jobId}  |  Generated: ${new Date().toLocaleDateString()}`),

        heading('Executive Summary'),
        body(insights.executiveSummary),

        heading('Key Discussion Points'),
        ...insights.keyPoints.map((p, i) => body(`${i + 1}. ${p}`)),

        heading('Decisions Made'),
        ...(insights.decisions.length > 0
          ? insights.decisions.map((d, i) => body(`${i + 1}. ${d}`))
          : [body('No explicit decisions recorded.')]),

        heading('Action Items'),
        ...(insights.actionItems.length > 0
          ? insights.actionItems.map((a, i) => {
              const owner = a.assignedSpeaker ? ` [${a.assignedSpeaker}]` : '';
              return body(`${i + 1}.${owner} ${a.description}`);
            })
          : [body('No action items recorded.')]),

        heading('Highlights'),
        ...insights.highlights.map((h, i) => body(`${i + 1}. ${h}`)),

        heading('Language Note'),
        body(`Original: ${insights.languageNote.originalLanguages.join(', ')} → Output: ${insights.languageNote.outputLanguage} (${insights.languageNote.localizationLevel})`),

        heading('Full Transcript'),
        ...segments.map((s) => {
          const time = s.startMs != null ? `[${msToReadable(s.startMs)}] ` : '';
          const speaker = s.speakerLabel ?? 'Speaker';
          const text = s.localizedText ?? s.originalText;
          return body(`${time}${speaker}: ${text}`);
        }),
      ],
    }],
  });

  return await Packer.toBuffer(doc);
}

// ── Storage Upload ─────────────────────────────────────────────────────────────

export async function uploadExport(
  jobId: string,
  format: 'txt' | 'srt' | 'pdf' | 'docx',
  content: Buffer | string,
  bucket: string
): Promise<{ path: string; fileName: string }> {
  const mimeTypes = {
    txt: 'text/plain',
    srt: 'text/plain',
    pdf: 'application/pdf',
    docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  };

  const fileName = `meeting-insights-${jobId}.${format}`;
  const path = `exports/${jobId}/${fileName}`;
  const buffer = typeof content === 'string' ? Buffer.from(content, 'utf-8') : content;

  const { error } = await supabaseAdmin.storage
    .from(bucket)
    .upload(path, buffer, {
      contentType: mimeTypes[format],
      upsert: true,
    });

  if (error) throw new Error(`Failed to upload ${format} export: ${error.message}`);

  await supabaseAdmin.from('meeting_insight_exports').upsert({
    job_id: jobId,
    format,
    bucket,
    path,
    file_name: fileName,
    mime_type: mimeTypes[format],
    size_bytes: buffer.length,
    created_at: new Date().toISOString(),
  }, { onConflict: 'job_id,format' });

  return { path, fileName };
}
